PCM_Module/Controllers/PCMCaseController.cs
using Common_Objects;
using Common_Objects.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Common_Objects.ViewModels;
using Novacode;
using Spire.Doc;
using System.Diagnostics;

namespace PCM_Module.Controllers
{
    public class PCMCaseController : Controller
    {
        #region Child Details
        public ActionResult Index(int id)
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            //instanciate model repositry
            PCMCaseModel caseModel = new PCMCaseModel();

            //instanciate viewmodel
            PCMPersonViewModel personVM = new PCMPersonViewModel();

            //get person id by assessment id
            int personId = caseModel.GetPCMPersonIdByintAssId(id);

            //get person record
            personVM = caseModel.GetPCMPerson(personId);

            int ClientRefid = caseModel.GetClientRefIdssId(id);
            //Get Module Reference number ....................
            string ClientRef = caseModel.GetClientRef(ClientRefid);
            Session["ClientRef"] = ClientRef;
            var personIdUpdate = personId;
            if (ClientRef == null || ClientRef == "")
            {
                #region CreateReferenceNumber

                var dbContext = new SDIIS_DatabaseEntities();
                #region ObtainProvinceOfLoggedInUser
                //var currentUser = (User)Session["CurrentUser"];
                var userName = string.Empty;
                var currentUserProvinceId = -1;
                //if (currentUser != null)
                //{
                //    userName = currentUser.User_Name;
                //}
                //if (currentUser.Employees.Any())
                //    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                #endregion
                ClientModel clientModel = new ClientModel();
                int client_ID = dbContext.Intake_Assessments.Find(id).Client_Id;
                int module_ID = Convert.ToInt32(dbContext.Problem_Sub_Categories.Find(dbContext.Intake_Assessments.Find(id).Problem_Sub_Category_Id).Module_Id);
                var CheckExist = (from a in dbContext.int_Client_Module_Registration
                                  where a.Client_Id == client_ID && a.Module_Id == module_ID
                                  select a).ToList();
                if (CheckExist.Count() == 0)
                {
                    int ProblemCatId = dbContext.Problem_Sub_Categories.Find(dbContext.Intake_Assessments.Find(id).Problem_Sub_Category_Id).Problem_Category_Id;
                    int_Client_Module_Registration Adopt_int_Client = new int_Client_Module_Registration();
                    //string ProvinceAbbr = dbContext.Provinces.Find(currentUserProvinceId).Abbreviation;
                    Adopt_int_Client.Client_Module_Ref_No = clientModel.CreatePCMReferenceNumber( DateTime.Now.Year.ToString(), ProblemCatId, client_ID);
                    Adopt_int_Client.Client_Id = client_ID;
                    Adopt_int_Client.Module_Id = module_ID;
                    dbContext.int_Client_Module_Registration.Add(Adopt_int_Client);
                    dbContext.SaveChanges();

                    ClientRefid = caseModel.GetClientRefIdssId(id);
                    //Get Module Reference number ....................
                    ClientRef = caseModel.GetClientRef(ClientRefid);
                }
                #endregion

            }

            Session["ClientRef"] = ClientRef;
            ViewBag.ModuleRef = ClientRef;



            //populate dropdown lists
            var idType = caseModel.GetAllIdentificationType();
            var languageType = caseModel.GetAllLanguageType();
            var genderType = caseModel.GetAllGenderType();
            var maritalType = caseModel.GetAllMaritalType();
            var contactType = caseModel.GetAllContactType();
            var religionType = caseModel.GetAllReligionType();
            var nationalityType = caseModel.GetAllNationalityType();
            var disabilityType = caseModel.GetAllDisabilityType();
            var populationGroup = caseModel.GetAllPopulationType();
            //var townType = caseModel.GetAllTownType();

            personVM.Identification_Type = idType;
            personVM.Language_Type = languageType;
            personVM.Gender_Type = genderType;
            personVM.Marital_Type = maritalType;
            personVM.Contact_Type = contactType;
            personVM.Religion_Type = religionType;
            personVM.Nationality_Group = nationalityType;
            personVM.Disability_Group = disabilityType;
            personVM.Population_Group = populationGroup;
            Session["PersonId"] = personIdUpdate;
            Session["Idassessment"] = id;

            return PartialView(personVM);
        }

        [HttpGet]
        public ActionResult UpdatePerson()
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            //initialise model
            PCMCaseModel caseModel = new PCMCaseModel();
            //initialise view model
            PCMPersonViewModel personVM = new PCMPersonViewModel();
            // Load Dropdown List calling the method in the model
            var personIdUpdate = Convert.ToInt32(Session["PersonId"]);
            var Idassessment = Convert.ToInt32(Session["Idassessment"]);

            //populate dropdown lists
            var idType = caseModel.GetAllIdentificationType();
            var languageType = caseModel.GetAllLanguageType();
            var genderType = caseModel.GetAllGenderType();
            var maritalType = caseModel.GetAllMaritalType();
            var contactType = caseModel.GetAllContactType();
            var religionType = caseModel.GetAllReligionType();
            var nationalityType = caseModel.GetAllNationalityType();
            var disabilityType = caseModel.GetAllDisabilityType();
            var populationGroup = caseModel.GetAllPopulationType();
            //var townType = caseModel.GetAllTownType();

            personVM.Identification_Type = idType;
            personVM.Language_Type = languageType;
            personVM.Gender_Type = genderType;
            personVM.Marital_Type = maritalType;
            personVM.Contact_Type = contactType;
            personVM.Religion_Type = religionType;
            personVM.Nationality_Group = nationalityType;
            personVM.Disability_Group = disabilityType;
            personVM.Population_Group = populationGroup;


            return PartialView("Assessment", personVM);
        }

        [HttpPost]
        public ActionResult UpdatePerson(PCMPersonViewModel UpdateCase)
        {

            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            var personIdUpdate = Convert.ToInt32(Session["PersonId"]);
            var Idassessment = Convert.ToInt32(Session["Idassessment"]);


            PCMCaseModel Model = new PCMCaseModel();

            //Call upadte function.........................................
            string myStringuserId = userId.ToString();
            Model.UpdatePersonalDetails(UpdateCase, myStringuserId, personIdUpdate);

            return RedirectToAction("Index", "Assessment", new { Id = Idassessment });
        }

        #endregion

        #region ADD UPDATE PCM CASE DETAILS

        #region GET CASE
        public ActionResult GetPCMCaseDetails(int id)
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }
            //initialise model repositry
            PCMCaseModel Model = new PCMCaseModel();

PCM_Module/Views/PCMDiversionSP/Index - Copy.cshtml
@model Common_Objects.ViewModels.PCMDiversionViewModel


@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary">
    

    @using (Html.BeginForm("addPreliminary", "PCMPreliminary", FormMethod.Post))
    {

        <div class="row">
            <div class="col-md-3">
                Intake Assessment Id
            </div>
            <div class="col-md-3 form-group">
                @Html.TextBoxFor(model => model.Intake_Assessment_Id, new { @id = "Intake_Assessment_Id", @class = "form-control jqueryui-marker-datepicker" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                Source_Referral
            </div>
            <div class="col-md-3 form-group">
                @*@Html.TextBoxFor(model => model.Source_Referral, new { @id = "Source_Referral", @class = "form-control jqueryui-marker-datepicker" })*@
                @Html.DropDownListFor(model => model.Source_Referral,
                                new List<SelectListItem> {
                       new SelectListItem { Value = "0" , Text = "-Select-" },
                       new SelectListItem { Value = "1" , Text = "Presecutor" },
                       new SelectListItem { Value = "2" , Text = "Probation Officer" }
                                  }, new { @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                Province
            </div>
            <div class="col-md-3 form-group">
                @Html.DropDownListFor(x => x.Province_Id, new SelectList(Model.Description_Type, "Province_Id", "Description"), "-Select Province-", new { @id = "Province_Id", @class = "form-control" })
            </div>
        </div>


        <div class="row">
            <div class="col-md-3">
                Service Provider
            </div>
            <div class="col-md-3 form-group">
                @Html.DropDownList("Service_Provider_Category", new SelectList(string.Empty, "Value", "Text"), "-Select Provider-", new { @id = "Service_Provider_Category", @class = "form-control" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                Service Provider Status
            </div>
            <div class="col-md-3 form-group">
                @Html.TextBoxFor(model => model.Intake_Assessment_Id, new { @id = "Intake_Assessment_Id", @class = "form-control jqueryui-marker-datepicker" })
            </div>
        </div>


        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-3 form-group">
                <a href="#" class="btn btn-block btn-success" id="SaveRecord">Save</a>
            </div>
        </div>

        @*<div class="form-group">
                <a href="#" class="btn btn-block btn-danger" id="SaveStudentRecord">Save</a>
            </div>*@
    }
</div>


    @*<script src="~/Scripts/jquery-1.7.1.js"></script>
        <script src="~/Scripts/jquery-1.7.1.min.js"></script>*@

    <script type="text/javascript">
    $(document).ready(function () {
        //Country Dropdown Selectedchange event
        $("#Province_Id").change(function () {
            $("#Service_Provider_Category").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetServicesP")', // Calling json method
                dataType: 'json',
                data: { id: $("#Province_Id").val() },
                // Get Selected Country ID.

                success: function (states) {
                    $.each(states, function (i, state) {
                        $("#Service_Provider_Category").append('<option value="' + state.Value + '">' + state.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })
    });
    </script>

PCM_Module/Views/PCMDiversionSP/Index_.cshtml
@model Common_Objects.ViewModels.PCMDiversionViewModel

<div class="tab-pane" id="tab3">

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default form-horizontal">
                <div class="panel-heading">
                    Service Provider And Programs Details
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("CreateDivesion", "PCMCase", new { id = Model.Intake_Assessment_Id }))
                    {
                        <div class="row">
                            <div class="col-md-3">
                                @Html.LabelFor(x => x.Province_Id)<span style="color:red; font-weight:bolder; font-size:20px">*</span>
                            </div>
                            <div class="col-md-6 form-group">
                                @Html.DropDownList("ProvincerD", ViewBag.Province_List as SelectList, "-- Please Select Province  --", new { @class = "form-control" })
                            </div>
                        </div>



                        <div class="row">
                            <div class="col-md-3">
                                @Html.LabelFor(x => x.District_Id)<span style="color:red; font-weight:bolder; font-size:20px">*</span>
                            </div>
                            <div class="col-md-6 form-group">
                                @Html.DropDownList("DistrictrD", new SelectList(string.Empty, "Value", "Text"), "-- Please select District --", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-3">
                                @Html.LabelFor(x => x.Local_Municipality_Id)<span style="color:red; font-weight:bolder; font-size:20px">*</span>
                            </div>
                            <div class="col-md-6 form-group">
                                @Html.DropDownList("LocalMunicipalityD", new SelectList(string.Empty, "Value", "Text"), "-- Please select Local Municipality --", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-3">
                                @Html.LabelFor(x => x.Organization_Id_Type)<span style="color:red; font-weight:bolder; font-size:20px">*</span>
                            </div>
                            <div class="col-md-6 form-group">
                                @Html.DropDownListFor(x => x.Organization_Id_Type, new SelectList(Model.OrganisationType_List, "Organization_Type_Id", "Description"), "-Select Organisation Type-", new { @id = "DropdownOrganizationTypeD", @class = "form-control", @required = "required" })
                                @Html.ValidationMessageFor(x => x.Organization_Id_Type, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="row">

                            <div class="col-md-3">
                                @Html.LabelFor(x => x.Organization_Id)<span style="color:red; font-weight:bolder; font-size:20px">*</span>
                            </div>
                            <div class="col-md-6 form-group">

                                @Html.DropDownList("DropdownOrganizationD", new SelectList(string.Empty, "Value", "Text"), "-- Please select Organisation --", new { @class = "form-control", @required = "required" })
                                @*@Html.DropDownListFor(x => x.Organization_Id, new SelectList(Model.PCMOrganisation_List, "Organization_Id", "Description"), "-Select Parent Organisation-", new { @id = "DropdownOrganization", @class = "form-control", @required = "required" })*@
                                @*@Html.ValidationMessageFor(x => x.Organization_Id, "", new { @class = "text-danger" })*@
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-3">
                                @Html.LabelFor(x => x.Div_Program_Id)<span style="color:red; font-weight:bolder; font-size:20px">*</span>
                            </div>

                            <div class="col-md-6 form-group">


                                @Html.ListBoxFor(x => x.Div_Program_Id, new SelectList(new SelectList(string.Empty, "Value", "Text"), "Div_Program_Id", "Programme_Name"), new
                                {
                                    @multiple = "multiple",
                                    @id = "SelCountry22D",
                                    @class = "listbox",
                                    @style = "width:450px;height:100px;border-radius:10px;outline: 0;-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);"
                                })
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="col-md-3">
                                <input type="submit" id="ButtonSave" value="Save" class="btn btn-success" />
                                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    }
                </div>
                @*<p>@Html.Action("GetSelectedProgrammesFromDBD", "PCMCase", new { @id = Convert.ToInt32(Session["CaseID"]) })</p>*@

            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    var k = jQuery.noConflict();
    k(function () {
        k('#SelCountry22D').multiselect({
            includeSelectAllOption: true
        });
    });
</script>



<script type="text/javascript">
    $(document).ready(function () {
        //Country Dropdown Selectedchange event
        $("#DropdownOrganizationTypeD").change(function () {
            $("#DropdownOrganizationD").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetOrganisationsD")', // Calling json method

                dataType: 'json',

                data: { id: $("#DropdownOrganizationTypeD").val(), LocMunId: $("#LocalMunicipalityD").val() },
                // Get Selected Country ID.

                success: function (organisations) {

                    $.each(organisations, function (i, organi) {
                        $("#DropdownOrganizationD").append('<option value="' + organi.Value + '">' +
                             organi.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve Organisation.' + ex);
                }
            });
            return false;
        })
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        //Country Dropdown Selectedchange event

        $("#DropdownOrganizationD").change('sortupdate', function () {
            $("#SelCountry22D").empty();
            //$('#DropdownOrganization').trigger("chosen:updated");
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDivesionsD")', // Calling json method

                dataType: 'json',

                data: { id: $("#DropdownOrganizationD").val() },
                // Get Selected Country ID.

                success: function (organisations) {

                    $.each(organisations, function (i, organi) {
                        $("#SelCountry22D").append('<option value="' + organi.Value + '">' +
                             organi.Text + '</option>');
                    });

                },
                error: function (ex) {
                    alert('Failed to retrieve Organisation.' + ex);
                }
            });
            return false;
        })
    });
    $("#ProvincerD").change(function () {
        $("#DistrictrD").empty();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetDistrictsD")', // Calling json method
            dataType: 'json',
            data: { id: $("#ProvincerD").val() },
            // Get Selected Country ID.

            success: function (states) {
                $.each(states, function (i, state) {
                    $("#DistrictrD").append('<option value="' + state.Value + '">' +
                         state.Text + '</option>');
                });
            },
            error: function (ex) {
                alert('Failed to retrieve states.' + ex);
            }
        });
        return false;
    })


    $("#DistrictrD").change(function () {
        $("#LocalMunicipalityD").empty();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetLocalMunicipalitiesD")', // Calling json method
            dataType: 'json',
            data: { id: $("#DistrictrD").val() },
            // Get Selected Country ID.

            success: function (states) {
                $.each(states, function (i, state) {
                    $("#LocalMunicipalityD").append('<option value="' + state.Value + '">' +
                         state.Text + '</option>');
                });
            },
            error: function (ex) {
                alert('Failed to retrieve states.' + ex);
            }
        });
        return false;
    })
</script>

PCM_Module/Views/PCMDiversionSP/Programme.cshtml
@model Common_Objects.ViewModels.PCMDiversionViewModel

@{
    ViewBag.Title = "Index";
    //WebGrid webGrid = new WebGrid(source: Model, canPage: false, canSort: false);
}


@*<script src="~/Scripts/jquery-3.3.1.min.js"></script>*@
@*<script src="~/Scripts/bootstrap.min.js"></script>*@


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @using (Html.BeginForm("Programme", "PCMDiversion", FormMethod.Post))
    {
        <div class="row">
            <div class="col-md-3">
                Service Provider
            </div>
            <div class="col-md-3 form-group">
               @Html.DropDownList("ServicesProviderId", ViewBag.Country as SelectList, "-Select Services Provider-", new { style = "width:250px" }) 
            </div>
        </div>


        <div class="row">
            <div class="col-md-3">
                Programmes
            </div>
            <div class="col-md-3 form-group">
              
             @*@Html.DropDownList("ProgrammeId", new SelectList(string.Empty, "Value", "Text"), "-Select Programme-", new { style = "width:250px", multiple = "multiple", @class = "listbox" })*@
               
                <select id="myP" multiple="multiple" required name="ProgrammeId">
                    @if(ViewBag.myP != null)
                    {
                        foreach(var item in ViewBag.myP)
                        {
                            if(item.Text != null)
                            {
                                <option value="@item.Value"> @item.Text</option>
                            }
                        }
                    }
                </select>  


            </div>
        </div>

        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-3 form-group">
                <a href="#" class="btn btn-block btn-success" id="SaveRecord">Save</a>
                @*<input type="submit" value="Submit" />*@
            </div>
        </div>
    }
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>
    }
</body>
</html>

@*<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/bootstrap-multiselect.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>*@



<script type="text/javascript">

    $(document).ready(function () {
        //Country Dropdown Selectedchange event
        $("#ServicesProviderId").change(function () {
            $("#Programme_Id").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetProgrammes")', // Calling json method
                dataType: 'json',
                data: { id: $("#ServicesProviderId").val() },
                // Get Selected Country ID.

                success: function (states) {
                    $.each(states, function (i, state) {
                        $("#ProgrammeId").append('<option value="' + state.Value + '">' + state.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })
    });

    //$(function () {
    //    $('#ProgrammeId').multiselect({
    //        includeSelectAllOption: true
    //    });

    //    $('#btnSelected').click(function () {
    //        var selected = $("#ProgrammeId option:selected");
    //        var message = "";
    //        selected.each(function () {
    //            message += $(this).text() + " " + $(this).val() + "\n";
    //        });
    //        alert(message);
    //    });
    //});

    

</script>