PCM_Module/Controllers/PCMFCRproceedingController.cs
using Common_Objects.Models;
using Common_Objects.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PCM_Module.Controllers
{
    public class PCMFCRproceedingController : Controller
    {
        PCMFCRViewModel vm = new PCMFCRViewModel();
        PCMFCRModel m = new PCMFCRModel();


        SDIIS_DatabaseEntities db = new SDIIS_DatabaseEntities();



        // GET: PCMFCRproceeding
        public ActionResult Index(int id)
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            int? Recid = m.GetPlacementId(id);
            ViewBag.Message = Recid;


            PCMFCRModel Model = new PCMFCRModel();
            PCMFCRViewModel vm = new PCMFCRViewModel();
            vm.PlacementRecomendation_List = Model.GetPlacementRecomendation();
            vm.Recommendation_Type_List = Model.GetRecommendationType();
            vm.Case_Type = Model.GetCaseStatus();
            ViewBag.Recommendation_Type_List = new SelectList(db.apl_Recommendation_Type.ToList(), "Recommendation_Type_Id", "Description");
            ViewBag.PlacementRecomendation_List = new SelectList(db.apl_Placement_Type.ToList(), "Placement_Type_Id", "Description");
            ViewBag.FormalCaseStatus_List = new SelectList(db.apl_PCM_Court_Case_Status.ToList(), "Court_Case_Status_Id", "Description");

            var CourtsType = m.GetCourtsType();
            vm.Courts_Type = m.GetCourtsType();
            var CaseType = m.GetCaseType();
            vm.Case_Type = m.GetCaseType();

            Session["Idc1"] = id;
            Session["IntakeassId"] = id;

            return PartialView(vm);
        }


        #region FORMAL COURT
        public JsonResult GetPCMFormalCourtList()
        {

            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            int assID = Convert.ToInt32(Session["IntakeassId"]);
            return Json(m.GetPCMFormalCourtList(assID), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetProceedingById(int FormalCourt_Id)
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            int assID = Convert.ToInt32(Session["IntakeassId"]);
            db.Configuration.LazyLoadingEnabled = false;

            PCM_FCR_Proceeding model = db.PCM_FCR_Proceeding.Where(x => x.FormalCourt_Id == FormalCourt_Id).SingleOrDefault();
            string value = string.Empty;
            value = JsonConvert.SerializeObject(model, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Json(value, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddProceeding(PCMFCRViewModel vm)
        {

            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            int assID = Convert.ToInt32(Session["IntakeassId"]);

            PCMFCRModel m = new PCMFCRModel();

            int Intake_Assessment_Id = assID;
            var result = false;

            try
            {
                if (vm.FormalCourt_Id > 0)
                {
                    m.UpdateProceeding(vm, vm.FormalCourt_Id, Intake_Assessment_Id, userId);
                    result = true;
                }
                else
                {
                    m.AddProceeding(vm, Intake_Assessment_Id, userId);
                    result = true;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region FORMAL COURT OUTCOME

        public ActionResult IndexOutcome()
        {
            var CaseType = m.GetCaseType();
            vm.Case_Type = m.GetCaseType();
            return PartialView(vm);
        }

        public JsonResult GetPCMFCRoutcome()
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }
            int assID = Convert.ToInt32(Session["IntakeassId"]);
            PCMFCRModel Model = new PCMFCRModel();
            PCMFCRViewModel vm = new PCMFCRViewModel();
            vm.PlacementRecomendation_List = Model.GetPlacementRecomendation();
            vm.Recommendation_Type_List = Model.GetRecommendationType();
            vm.Case_Type = Model.GetCaseStatus();
            ViewBag.Recommendation_Type_List = new SelectList(db.apl_Recommendation_Type.ToList(), "Recommendation_Type_Id", "Description");
            ViewBag.PlacementRecomendation_List = new SelectList(db.apl_Placement_Type.ToList(), "Placement_Type_Id", "Description");
            ViewBag.FormalCaseStatus_List = new SelectList(db.apl_PCM_Court_Case_Status.ToList(), "Court_Case_Status_Id", "Description");

            return Json(m.GetPCMFCRoutcome(assID), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetOutcomeById(int FormalCourtOutcome_Id)
        {
            db.Configuration.LazyLoadingEnabled = false;

            PCMFCRModel Model = new PCMFCRModel();
            PCMFCRViewModel vm = new PCMFCRViewModel();
            vm.PlacementRecomendation_List = Model.GetPlacementRecomendation();
            vm.Recommendation_Type_List = Model.GetRecommendationType();
            vm.Case_Type = Model.GetCaseStatus();
            ViewBag.Recommendation_Type_List = new SelectList(db.apl_Recommendation_Type.ToList(), "Recommendation_Type_Id", "Description");
            ViewBag.PlacementRecomendation_List = new SelectList(db.apl_Placement_Type.ToList(), "Placement_Type_Id", "Description");
            ViewBag.FormalCaseStatus_List = new SelectList(db.apl_PCM_Court_Case_Status.ToList(), "Court_Case_Status_Id", "Description");


            vm = Model.GetFormalCourtById(FormalCourtOutcome_Id);
            string value = string.Empty;
            value = JsonConvert.SerializeObject(vm, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Json(value, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddOutcome(PCMFCRViewModel vm)
        {

            //get current username

PCM_Module/Controllers/PCMPretrailController.cs
using Common_Objects.Models;
using Common_Objects.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PCM_Module.Controllers
{
    public class PCMPretrailController : Controller
    {
        PCMPretrailModel ppm = new PCMPretrailModel();
        PCMPretrailViewModel pVM = new PCMPretrailViewModel();

        SDIIS_DatabaseEntities db = new SDIIS_DatabaseEntities();

        // GET: PCMPretrail/home
        public ActionResult Home(int id)
        {

            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            //instanciate model repositry
            PCMCaseModel caseModel = new PCMCaseModel();

            //instanciate viewmodel
            PCMPersonViewModel personVM = new PCMPersonViewModel();

            //get person id by assessment id
            personVM.IntakeAssPar = id;


            int ClientRefid = caseModel.GetClientRefIdssId(id);
            //Get Module Reference number ....................
            string ClientRef = caseModel.GetClientRef(ClientRefid);
            Session["ClientRef"] = ClientRef;
            ViewBag.ModuleRef = ClientRef;

            return View(personVM);
        }
        // GET: PCMPretrail
        public ActionResult Index()
        {

            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            string ClientRef = Convert.ToString(Session["ClientRef"]);
            ViewBag.ModuleRef = ClientRef;


            var outcomeType = ppm.GetOutcomeType();
            pVM.Outcome_Type = ppm.GetOutcomeType();

            return PartialView(pVM);
        }
        public JsonResult ListAll()
        {
            return Json(ppm.ListAll(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPretrialById(int PCM_Pretrial_Id)
        {
            db.Configuration.LazyLoadingEnabled = false;

            PCM_Pretrial_Details model = db.PCM_Pretrial_Details.Where(x => x.PCM_Pretrial_Id == PCM_Pretrial_Id).SingleOrDefault();
            string value = string.Empty;
            value = JsonConvert.SerializeObject(model, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Json(value, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add(PCMPretrailViewModel pVM)
        {

            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }

            int assID = Convert.ToInt32(Session["IntakeassId"]);

            PCMPretrailModel pM = new PCMPretrailModel();
           
            int Intake_Assessment_Id = assID;
           
            var result = true;

            try
            {
                if(pVM.PCM_Pretrial_Id > 0)
                {
                    //pM.View(pVM, userId, p);
                    pM.update(pVM, pVM.PCM_Pretrial_Id, Intake_Assessment_Id, userId); 
                }
                else
                {
                    pM.Add(pVM, Intake_Assessment_Id, userId);
                    result = true;
                }
            }
            catch(Exception ex)
            {
                throw ex;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetbyID(int ID)
        {
            var gID = ppm.ListAll().Find(x => x.PCM_Pretrial_Id.Equals(ID));
            return Json(gID, JsonRequestBehavior.AllowGet);
        }
       
    }
}

PCM_Module/Controllers/PCMTabHBSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PCM_Module.Controllers
{
    public class PCMTabHBSController : Controller
    {
        // GET: PCMTabHBS
        public ActionResult Index()
        {
            return PartialView();
        }
    }
}

PCM_Module/Views/PCMPreliminary/AssessmentRecomendation.cshtml
@model Common_Objects.ViewModels.PCMCaseDetailsViewModel

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default form-horizontal">
            <div class="panel-heading">
                Assessment Recomendation
            </div>
            <div class="panel-body">

                <div class="row">

                    <div class="col-md-4">
                        @Html.LabelFor(x => x.Recommendation_Type_Id)<span style="color:red; font-weight:bolder; font-size:20px">*</span>
                    </div>
                    <div class="col-md-4 form-group">

                        @Html.DropDownListFor(x => x.Recommendation_Type_Id, new SelectList(Model.RecommendationTyp_List, "Recommendation_Type_Id", "Description"), "-Select Recomendation-", new { @id = "DropdownRecop", @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(x => x.Recommendation_Type_Id, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="row">

                    <div class="col-md-4">
                        @Html.LabelFor(x => x.Comments_For_Recommendation)
                    </div>
                    <div class="col-md-4 form-group">

                        @Html.TextAreaFor(x => x.Comments_For_Recommendation, new { @id = "RecomComentsp", rows = "2", @class = "form-control", @required = "required" })
                    </div>

                </div>
                <div class="row">
                    <div id="Plcement">
                        <div class="col-md-4">
                            @Html.LabelFor(x => x.Placement_Type_Id)
                        </div>
                        <div class="col-md-4 form-group">

                            @Html.DropDownListFor(x => x.Placement_Type_Id, new SelectList(Model.PlacementType_List, "Placement_Type_Id", "Description"), "-Select Placement-", new { @id = "DropdownPlacementp", @class = "form-control" })

                        </div>
                    </div>
                </div>
          
            </div>

        </div>
    </div>
</div>


<script>

    $(function () {

        $("#DropdownRecop").prop("disabled", true);
        $("#DropdownPlacementp").prop("disabled", true);
        $("#RecomComentsp").prop("disabled", true);
        

    });
</script>

PCM_Module/Views/PCMPreliminary/CreatePreliminaryDetails.cshtml
@model Common_Objects.ViewModels.PCMPreliminaryViewModel
<br />

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("PCMCreatePreliminary", "PCMPreliminary"))
    {
        @Html.AntiForgeryToken()
        <div class="panel panel-primary">
            <div class="panel-heading" style="text-align: center">
                Case Details
            </div>
            <div class="panel-body">




            </div>
            <div class="form-group">
                <input type="submit" id="ButtonSave" value="Save" class="btn btn-success" />
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
            </div>

        </div>

    }

PCM_Module/Views/PCMPreliminary/GetOffence.cshtml
@model IEnumerable<Common_Objects.ViewModels.PCMPreliminaryViewModel>

@using GridMvc.Html
@{
    ViewBag.Title = "General Details";
}

@*<h2>PCM_Offence_Details</h2>*@



<div class="row">
    <div class="col-md-12">
        @Html.Grid(Model).Columns(columns =>
   {
   columns.Add(x => x.PCM_Offence_Id).Titled("PCM_Offence_Id");
   columns.Add(x => x.PCM_Case_Id).Titled("PCM_Case_Id");
   columns.Add(x => x.Intake_Assessment_Id).Titled("Intake_Assessment_Id");
   //columns.Add(x => x.Intake_Assessment_Id).Titled("Intake Assessment Id");
   //columns.Add(x => x.Recomendation_Order_Id).Titled("Recomendation Order Id").Sortable(true);
   //columns.Add(x => x.Person_Id).Titled("Person Id").Sortable(true);
   //columns.Add(x => x.Type_Of_Center_Id).Titled("Type Of Center Id").Sortable(true);

   columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(d => @<b> @Html.ActionLink("Offense", "addpreliminary", "PCMPreliminary", new { id = d.Intake_Assessment_Id }, new { @class = "btn btn-info pull-right" }) </b>);
    @* columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(d => @<b> @Html.ActionLink("Delete", "DeleteST", new { id = d.studID }, new { @class = "btn btn-info pull-right" }) </b>);
        columns.Add().Encoded(false).Sanitized(false).SetWidth(30).RenderValueAs(d => @<b> @Html.ActionLink("Add Subject", "Index", "Stud", new { id = d.studID }, new { @class = "btn btn-info pull-right" }) </b>);*@

   }).WithPaging(5)
    </div>
</div>

PCM_Module/Views/PCMPreliminary/Home.cshtml
@{
    ViewBag.Title = "Preliminary Inquiry";
}

@{
    var PlacementID = ViewBag.MessagePlacement;

}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>


<style>
    /* Styles for your <ul> menu */
    #headerPre ul {
        background: #F6F6F6;
        margin: 0 auto;
        padding: 28px 0 0;
        text-align: center;
        width: auto;
    }

        /* Styles for individual <li> elements */
        #headerPre ul li {
            display: inline;
            list-style: none;
            margin: 0;
            padding: 0;
        }



            /* Hover style for your links */
            #headerPre ul li a:hover {
                background: #3D515F !important;
                border-radius: 5px;
                color: black;
            }

            /* A more specific style for your "active" link */
            #headerPre ul li a.active {
                background-color: #008CBA !important;
                border-color: #000000;
                border-bottom: 5px solid #9b0e0e;
            }

                /* Specific hover style for your active link */
                #headerPre ul li a.active:hover {
                    color: yellow;
                }

    .nav-tabs > li.active > a,
    .nav-tabs > li.active > a:focus,
    .nav-tabs > li.active > a:hover {
        background-color: #008CBA !important;
        color: #fff;
    }
</style>



<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" id="drop5" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false" style="font-size:larger; font-weight:bolder ">NAVIGATION MENU<span class="caret"></span></a>
                    <ul class="dropdown-menu" id="menu2P" aria-labelledby="drop5">
                        <li><a href="../../Assessment/Index/@Model.IntakeAssPar">Assessment</a></li>
                        <li><a href="../../PCMPreliminary/Home/@Model.IntakeAssPar">Court Processes</a></li>
                        <li><a href="../../PCMHBS/Home/@Model.IntakeAssPar">Home Base Supervision</a></li>
                        <li><a href="../../Diversion/HomeIndex/@Model.IntakeAssPar">Diversion</a></li>
                        <li><a href="../../PCMPretrail/Home/@Model.IntakeAssPar">Pre-Trial</a></li>
                        <li><a href="../../Assessment/IndexPre/@Model.IntakeAssPar">Pre-sentence</a></li>
                        <li><a href="../../PCMReferrals/Home/@Model.IntakeAssPar">Referrals</a></li>
                    </ul>
                </li>
            </ul>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div id="rootwizard" style="height:auto;">

    <div id="headerPre">



        <ul class="nav nav-tabs" data-tabs="tabs" id="myTab222Pre">

            <li id="t2Pre">
                <a data-toggle="tab" href="#OffPre" aria-selected="true" data-id="OffPre" data-tab="tab1" id="Two">Offense Deatils</a>
            </li>
            <li id="t1Pre">
                <a data-toggle="tab" href="#homePre" aria-selected="true" data-id="homePre" data-tab="tab1" id="one">Preliminary Inquiry And Court Proceedure</a>
            </li>



        </ul>
    </div>

    <div class="tab-content" id="section">
        <div class="tab-pane" id="homePre" role="tabpanel">
            <h3>Preliminary Inquiry And Court Proceedure</h3>
            <p>@Html.Action("Index", "PCMPreliminary")</p>

        </div>

        <div class="tab-pane fade in active" id="OffPre" role="tabpanel">
            <h3>Offense Details</h3>
            <p>@Html.Action("OffencedeatailsListPre", "PCMPreliminary")</p>

        </div>


    </div>

</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")


<script type="text/javascript">

    $(document).ready(function () {
        $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
            localStorage.setItem('activeTab', $(e.target).attr('href'));
        });
        var activeTab = localStorage.getItem('activeTab');
        if (activeTab) {
            $('#myTab222Pre a[href="' + activeTab + '"]').tab('show');
        }


    });

    localStorage.setItem("Tab", "");

 




    $('#myTab222Pre a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });



    $('#myTab222P a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });


    function ajaxindicatorstop() {
        jQuery('#resultLoading .bg').height('100%');
        jQuery('#resultLoading').fadeOut(300);
        jQuery('body').css('cursor', 'default');
    }

    function ajaxindicatorstart(text) {
        var spinnerLocation = $.url('/Images/ajax-loader.gif');

        if (jQuery('body').find('#resultLoading').attr('id') != 'resultLoading') {
            jQuery('body').append('<div id="resultLoading" style="display:none"><div><img src="' + spinnerLocation + '"><div>' + text + '</div></div><div class="bg"></div></div>');
        }

        jQuery('#resultLoading').css({
            'width': '100%',
            'height': '100%',
            'position': 'fixed',
            'z-index': '10000000',
            'top': '0',
            'left': '0',
            'right': '0',
            'bottom': '0',
            'margin': 'auto'
        });

        jQuery('#resultLoading .bg').css({
            'background': '#000000',
            'opacity': '0.7',
            'width': '100%',
            'height': '100%',
            'position': 'absolute',
            'top': '0'
        });

        jQuery('#resultLoading>div:first').css({
            'width': '250px',
            'height': '75px',
            'text-align': 'center',
            'position': 'fixed',
            'top': '0',
            'left': '0',
            'right': '0',
            'bottom': '0',
            'margin': 'auto',
            'font-size': '16px',
            'z-index': '10',
            'color': '#ffffff'

        });

        jQuery('#resultLoading .bg').height('100%');
        jQuery('#resultLoading').fadeIn(300);
        jQuery('body').css('cursor', 'wait');
    }

    jQuery(document).ajaxStart(function () {
        //show ajax indicator
        ajaxindicatorstart('loading data.. please wait..');
    }).ajaxStop
        (function () {
            //hide ajax indicator
            ajaxindicatorstop();
        });
 

</script>

PCM_Module/Views/PCMPreliminary/IndexTabs.cshtml
@model Common_Objects.ViewModels.PCMPreliminaryViewModel

<html lang="en">
<head>


</head>
<body>

   

    <div id="tabs-2" class="tab-pane fade in active">

        <div>

            @{
                var data = ViewBag.Message;

                var PCM_Recommendation_Id = data;
            }
            @if (PCM_Recommendation_Id == 2)
            {

                @Html.Action("Index", "PCMChildrensCourt", new { @idrec = PCM_Recommendation_Id });
            }
            else if (PCM_Recommendation_Id == 3)
            {
               
                @Html.Action("Index", "PCMFCRproceeding", new { @idrec = PCM_Recommendation_Id });
            }
            else if (PCM_Recommendation_Id == 4)
            {

                // @Html.Action("Index", "PCMTabHBS");
            }
            else if (PCM_Recommendation_Id == 5)
            {
                // <p> CYCC.</p>
            }
            else
            {
                <header>Please Note </header>


                <p>Court Proceedures Contet Is Displayed Based Preliminary Inquiry Information .</p>
            }

        </div>
    </div>



</body>
</html>

<div id="tabs-3" class="tab-pane fade in active">
    @*@Html.Action("Index", "PCMPretrail");*@
</div>