PCM_Module/Controllers/PCMPresentence_SentenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common_Objects.ViewModels;
using Common_Objects;
using Common_Objects.Models;
using Newtonsoft.Json;

namespace PCM_Module.Controllers
{
    public class PCMPresentence_SentenceController : Controller
    {
        // GET: PCMPresentence_Sentence
        #region Child Details
        public ActionResult IndexPresentence(int id)
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            //instanciate model repositry
            PCMPresentenceModel caseModel = new PCMPresentenceModel();

            //instanciate viewmodel
            PCMPersonViewModel personVM = new PCMPersonViewModel();
            PCMCaseModel caseModelC = new PCMCaseModel();
            //get person id by assessment id
            int personId = caseModel.GetPCMPersonIdByintAssId(id);

            //get person record
            personVM = caseModel.GetPCMPerson(personId);

            int ClientRefid = caseModelC.GetClientRefIdssId(id);
            //Get Module Reference number ....................
            string ClientRef = caseModelC.GetClientRef(ClientRefid);
            Session["ClientRef"] = ClientRef;
            ViewBag.ModuleRef = ClientRef;
            return PartialView(personVM);
        }

        #endregion

        #region PRESENTENCE SUMMARY

        #region GET SUMMARY
        public ActionResult GetPCMPresentenseSummaryDetails(int id)
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }
        
            
            //initialise model repositry
            PCMPresentenceModel Model = new PCMPresentenceModel();

            //initialise view model
            PCMCaseModel caseModelC = new PCMCaseModel();

            string ClientRef = Convert.ToString(Session["ClientRef"]);
            ViewBag.ModuleRef = ClientRef;

            int PreSummaryID = Model.GetPCMPresentenseSummaryByassId(id);
            if (PreSummaryID != 0)
            {
                PCMPresentenceDetailsViewModel VM1 = new PCMPresentenceDetailsViewModel();
                VM1 = Model.GetPresentenseSummaryList(PreSummaryID);//.............................?
                
                Session["Idc1"] = PreSummaryID;
                Session["IntakeassId"] = id;
                return PartialView(VM1);
            }
            else
            {


                PCMPresentenceModel Model1 = new PCMPresentenceModel();
                PCMPresentenceDetailsViewModel VM = new PCMPresentenceDetailsViewModel();
                //initialise view model
                PCMPresentenceDetailsViewModel VMC = new PCMPresentenceDetailsViewModel();
                
                Model.InsertPresentenceSummaries(VM, id, userId);

                int PreSummaryID1 = Model1.GetPCMPresentenseSummaryByassId(id);
                
                VMC = Model1.GetPresentenseSummaryList(PreSummaryID1);

                Session["NewId"] = id;
                Session["IntakeassId"] = id;
                return PartialView(VMC);
            }

        }
        #endregion

        #region UPDATE Summary DETAILS


        [HttpGet]
        public ActionResult UpdatePresentenceSummaries()
        {
            //get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

            if (currentUser != null)
            {
                userId = currentUser.User_Id;
                if (currentUser.Employees.Any())
                {
                    userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
                if (currentUser.apl_Social_Worker.Any())
                {
                    userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
                }
            }
            //initialise model repositry
            PCMPresentenceModel Model = new PCMPresentenceModel();

            //initialise view model
            PCMPresentenceDetailsViewModel VM = new PCMPresentenceDetailsViewModel();



            return PartialView("GetPCMPresentenseSummaryDetails", VM);

        }

        [HttpPost]
        public ActionResult UpdatePresentenceSummaries(PCMPresentenceDetailsViewModel caseVM)
        {
            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

    if (currentUser != null)
    {
        userId = currentUser.User_Id;
        if (currentUser.Employees.Any())
        {
            userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
        }
        if (currentUser.apl_Social_Worker.Any())
        {
            userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
        }
    }
    int id =Convert.ToInt32(Session["IntakeassId"]) ;
            int idcreate = Convert.ToInt32(Session["NewId"]);

            int Idupdate = Convert.ToInt32(Session["Idc1"]);
            int Id;
            if (Idupdate != 0)
            {

                Id = Idupdate;
            }
            else
            {
                Id = idcreate;
            }

            //instanciate model repositry
            PCMPresentenceModel Model = new PCMPresentenceModel();

            if (ModelState.IsValid)
            {
                // Call Update Function
                Model.UpdatePresentenceSummaries(caseVM, userId, Id);
                ViewBag.Message = "Updated successfully";
            }
            else
            {
                ViewBag.Message = "not updated ";
            }
            //return View("UpdatePCMCase", caseVM);
            return RedirectToAction("IndexPre", "Assessment", new { Id = id });
        }

        public ActionResult checkAssessmentId(int assID)
        {
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;

            ////instanciate model
            PCMPresentenceModel pcmcasemodel = new PCMPresentenceModel();

            ////instanciate viewmodel
            PCMPresentenceDetailsViewModel pcmcasevm = new PCMPresentenceDetailsViewModel();

            int SummId = pcmcasemodel.GetPCMPresentenseSummaryByassId(assID);
            if (SummId != 0)
            {
                return PartialView(pcmcasevm);
            }
            else
            {
                return PartialView(pcmcasevm);
            }
        }


        #endregion

        #endregion

        #region PRESENTENCE

        #region ADD UPDATE PRESENTENCE DETAILS

        public ActionResult GetPCMPresentense()
        {
            int intassid = Convert.ToInt32(Session["IntakeassId"]);
            // get current username
            string loginName = User.Identity.Name;
            Session["LoginName"] = loginName;
            var currentUser = (User)Session["CurrentUser"];
            var userProvince = -1;
            var userId = 0;

    if (currentUser != null)
    {
        userId = currentUser.User_Id;
        if (currentUser.Employees.Any())
        {
            userProvince = currentUser.Employees.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
        }
        if (currentUser.apl_Social_Worker.Any())
        {
            userProvince = currentUser.apl_Social_Worker.First().apl_Service_Office.apl_Local_Municipality.District.Province_Id;
        }
    }
    PCMCaseModel caseModelC = new PCMCaseModel();

            string ClientRef = Convert.ToString(Session["ClientRef"]);
            ViewBag.ModuleRef = ClientRef;

            PCMPresentenceModel Model = new PCMPresentenceModel();
            //initialise view model
            PCMPresentenceDetailsViewModel VM = new PCMPresentenceDetailsViewModel();

            using (SDIIS_DatabaseEntities db = new SDIIS_DatabaseEntities())
            {
                int Presentenseid = Model.GetPCMPresentenseByassId(intassid);
                if (Presentenseid != 0)
                {

                    VM = Model.GetPresentenseList(Presentenseid);

                    //populate dropdown lists

                    VM.CommunityBasedOptions_List = Model.GetCommunityBasedOption();
                    VM.SupendedPostponedSentence_List = Model.GetSupendedPostponedSentence();
                    VM.CaseStatus_List = Model.GetCaseStatus();//..................?
                    VM.RestorectiveJustice_List = Model.GetRestorectiveJustice();
                    VM.ProgrammeType_List = Model.GetProgrammeType();
                    VM.Programme_List = Model.GetProgramme();
                    VM.Imprisoment_List = Model.GetImprisoment();//..................?
                    VM.Department_List = Model.GetDepartment();
                    VM.Court_List = Model.GetAllCourt();
                    VM.Province_List = Model.GetAllProvinces();

PCM_Module/Views/PCMPresentence_Sentence/GetPCMPresentenseSummaryDetails.cshtml
@model Common_Objects.ViewModels.PCMPresentenceDetailsViewModel
<br />

@using (Html.BeginForm("UpdatePresentenceSummaries", "PCMPresentence_Sentence", new { id = Model.Intake_Assessment_Id }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading" style="text-align: center">
            Assessment Summary: <span style="color:white;font-weight: bolder; font-size:large; text-shadow: 2px 2px grey; ">Child Ref (@ViewBag.ModuleRef)</span>
        </div>
        <div class="panel-body">

            <div class="row">
                <div class="col-md-2">
                    @Html.LabelFor(x => x.IsAssessed)
                </div>
                <div class="col-md-4 form-group">
                  

                        @Html.RadioButtonFor(e => e.IsAssessed, true, new { id = "married-true" })
                        @Html.Label("married-true", "Yes")

                        @Html.RadioButtonFor(e => e.IsAssessed, false, new { id = "married-false" })
                        @Html.Label("married-false", "No")

                </div>
                <div class="col-md-2">
                    @Html.LabelFor(x => x.Education_Sammary)
                </div>
                <div class="col-md-4 form-group">
                    @Html.TextAreaFor(x => x.Education_Sammary, new { @id = "Education_Sammary", @class = "form-control", rows = "5", @required = "required" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    @Html.LabelFor(x => x.Offence_Sammary)
                </div>
                <div class="col-md-4 form-group">
                    @Html.TextAreaFor(x => x.Offence_Sammary, new { @id = "Offence_Sammary", @class = "form-control", rows = "5", @required = "required" })
                </div>

                <div class="col-md-2">
                    @Html.LabelFor(x => x.Victim_Sammary)
                </div>
                <div class="col-md-4 form-group">
                    @Html.TextAreaFor(x => x.Victim_Sammary, new { @id = "Victim_Sammary", @class = "form-control", rows = "5", @required = "required" })
                </div>
            </div>


        </div>
        <div class="form-group">
            <input type="submit" id="ButtonSave" value="Save" class="btn btn-success" />
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
        </div>

    </div>

}

PCM_Module/Views/PCMPresentence_Sentence/IndexPresentence.cshtml
@model Common_Objects.ViewModels.PCMPersonViewModel


<head>

 
</head>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        @Html.HiddenFor(model => model.Person_Id, new { id = "Person_Id" })
        <div class="panel-heading" style="text-align: center">
            Child Details: <span style="color:white;font-weight: bolder; font-size:large; text-shadow: 2px 2px grey; ">Child Ref (@ViewBag.ModuleRef)</span>
        </div>
        <div class="panel-body">

            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(x => x.First_Name)
                </div>
                <div class="col-md-3 form-group">
                    @Html.TextBoxFor(x => x.First_Name, new { @id = "ClientFirstName", @class = "form-control", @required = "required" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(x => x.Last_Name)
                </div>
                <div class="col-md-3 form-group">
                    @Html.TextBoxFor(x => x.Last_Name, new { @id = "ClientLastName", @class = "form-control", @required = "required" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(x => x.Date_Of_Birth, new { @id = "LabelDateOfBirth", @class = "control-label" })
                </div>
                <div class="col-md-3 form-group">
                    <div class="input-group">
                        @Html.TextBoxFor(x => x.Date_Of_Birth, new { @id = "Date_of_Birth", @class = "form-control jqueryui-marker-datepicker" })
                        <label for="Date_of_Birth" class="input-group-addon btn">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </label>
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(x => x.Identification_Number)
                </div>
                <div class="col-md-3 form-group">
                    @Html.TextBoxFor(x => x.Identification_Number, new { @class = "form-control" })
                </div>
            </div>

        </div>
 
    </div>
}


    <script type="text/javascript">
        $(document).ready(function () {

            // Initialize items marked as datepickers
            $(".jqueryui-marker-datepicker").datepicker({
                dateFormat: "dd M yy",
                changeYear: true
            });

        });

    </script>